Allow being provided a list of services to bound to the apps
philips-labs/terraform-cloudfoundry-thanos pull request #59
Opened 2022-01-19 19:35 UTC by l-lafin

I'm adding a variable to be possible to provide a list of services to be bound to the apps. Such a feature is needed for example to send the apps logs to the log bucket.

2022-01-19 19:41 UTC, jdelucaa requested changes

2022-01-19 19:41 UTC, jdelucaa commented on variables.tf
> +variable "thanos_query_service_bindings" {
duplicated

2022-01-19 20:00 UTC, l-lafin commented on variables.tf
> +variable "thanos_query_service_bindings" {
Removed 😃

2022-01-20 17:59 UTC, l-lafin commented
Hi @loafoe, could you have a look at this PR? I'm adding a configuration to allow us to connect a logging service to the apps.

2022-01-20 18:52 UTC, merged

2022-01-20 18:55 UTC, loafoe commented
@l-lafin merged and created a new release